# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyHouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.6.2', '<3.0'

end
